#!/bin/env python3
#  \________________________ PreProc

# This file exists to test out different color schemes in neovim 
# and to help us develop our own.
#

# TODO:
# FIXME:
# 

#.-
#|   .- Identifier
#|   |                                  .-         
#|   |                                  |        
#|   |                                  |      .- ?         
from somewhere                          import Something

#  __ Keyword    _____________ Type __ Special
# /             /          /       /
def func(arg1: str, arg2: int) -> None:
#    \    \__________\__ Identifier
#     \__ Function

    while True;
#    \    \__ Boolean
#     \__ Repeat
        pass
#        \__ Keywords

#   #.- Repeat
    for var in range(0, 1000):
        #.- Conditional
        if var is not None:
            return
        #.- Conditional
        else:
            #.- Repeat
            break

    #.- Exception
    try:
        pass
        #\__ Keywords
    #.- Exception
    except:
        pass
        #\__ Keywords

    #.- Identifier
    #|      .-----.--------.---.- Number
    var += 7000 + 12000 / (4 * 8)

    #      .- Function                                            .- Function
    m = re.match(r'^(\d+\.\d+\.\d+[\.-][\drc]+)-?(.*)$', platform.release())

STRING_CONSTANT = r'this is a constant'
STR2_CONSTANT = '''
         This is another string, this one is multiline and is defined by tripple quotes.
'''
CHARACTER_CONSTANT = '\n'
CC = 'x'

class AnError(Exception):
    def __init__(self, returncode, cmd, output):
        self.returncode = returncode
        self.command    = cmd
        self.output     = output

